# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19PSi1xR1yPg50OIvD1hBGAPeEYq6HTLg
"""

!pip install streamlit pyngrok

import streamlit as st
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

# App title
st.title("🎓 Placement Predictor Model")
st.write("Predict whether a student is likely to be placed based on academic and skill data.")

# Load dataset
data = pd.read_csv("/content/placement.csv")

# Split data
X = data.drop("Placement", axis=1)
y = data["Placement"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Train model
model = LogisticRegression()
model.fit(X_train, y_train)

st.subheader("📋 Enter Student Details")

# User inputs
cgpa = st.number_input("CGPA", min_value=0.0, max_value=10.0, step=0.1)
internships = st.number_input("Number of Internships", min_value=0, step=1)
projects = st.number_input("Number of Projects", min_value=0, step=1)
skills = st.slider("Skill Level (out of 10)", 0, 10)
aptitude = st.number_input("Aptitude Score", min_value=0, max_value=100, step=1)

# Predict button
if st.button("Predict Placement"):
    input_data = pd.DataFrame(
        [[cgpa, internships, projects, skills, aptitude]],
        columns=["CGPA", "Internships", "Projects", "Skills", "Aptitude"]
    )

    prediction = model.predict(input_data)

    if prediction[0] == 1:
        st.success("✅ Student is Likely to be Placed")
    else:
        st.error("❌ Student is Not Likely to be Placed")